### ISSUE TITLE
 Freeze router-tab__header position (Nuxt + vue-router-tab (Vuetify - googleContact admin example) )

### ISSUE THREAD

**Issue by urfinorg** [bhuh12/vue-router-tab#80]
Firstly, big thanks for the great job! vue-router-tab is really useful component!

I try to implement your component into Vuetify - "googleContact admin example" (now hide on Vuetify site)

I have problem with scroling, router-tab__header scroll together with router-tab__container and hide from screen. I create a small demo here:
https://codesandbox.io/s/distracted-lovelace-ck0g6?file=/layouts/default.vue

Can you look this? How to freeze router-tab__header position?

Thanks

**Comment by bhuh12** [comment]
https://codesandbox.io/s/cool-sammet-kk2n8?file=/layouts/default.vue

``` css
html {
  overflow-y: auto;
}

.router-tab {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```
